import Head from 'next/head'
import { useState } from "react";
import { 
  Wrapper,
  LogoContainer, LogoImg, LogoTitle,
  InputWrap, InputRemoveBtn, 
  EmailInput, EmailError, 
  PasswordInput, PasswordError,
  LoginBtn,
  AccountOption, AccountItem,
  SocialLoginBtn, SocialLoginImg, SocialLoginTitle
} from "../../styles/classQuiz02_5";

export default function ClassQuiz02_5() {

  const [email, setEmail] = useState('');
  const [emailError, setEmailError] = useState('');

  const [password, setPassword] = useState('');

  const [passwordError, setPasswordError] = useState('');



  function onChangeEmail(event) {
    setEmail(event.target.value);
  }
  function onChangePassword(event) {
    setPassword(event.target.value);
    console.log(password.length);
  }



  function onClickSignUp() {

    if (email === "") {
      setEmailError("이메일 주소를 다시 확인해주세요.");
    } else if(!email.includes("@")) {
      setEmailError("이메일 @이 없습니다.");
    } else {
      setEmailError("");
    }


    if (password === "") {
      setPasswordError("이메일 주소를 다시 확인해주세요.");
    } else if(password.length < 8 || password.length > 16) {
      setPasswordError("8~16자의 영문, 숫자, 특수 문자만 사용 가능합니다.");
    } else {
      setPasswordError("");
    }

  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Wrapper>
        <LogoContainer>
          <LogoImg src='../images/02/logo.png' ></LogoImg>
          <LogoTitle>잇츠로드</LogoTitle>
        </LogoContainer>

        <InputWrap>
          <EmailInput placeholder="이메일을 입력해주세요." onChange={onChangeEmail} />
          <InputRemoveBtn></InputRemoveBtn>
        </InputWrap>
        <EmailError>{emailError}</EmailError>

        <InputWrap>
          <PasswordInput type='password' onChange={onChangePassword} placeholder="비밀번호를 입력해주세요." />
          <InputRemoveBtn></InputRemoveBtn>
        </InputWrap>
        <PasswordError>{passwordError}</PasswordError>

        <LoginBtn onClick={onClickSignUp}>로그인</LoginBtn>
        
        <AccountOption>
          <AccountItem>이메일 찾기</AccountItem>
          <AccountItem>|</AccountItem>
          <AccountItem>비밀번호 찾기</AccountItem>
          <AccountItem>|</AccountItem>
          <AccountItem>회원가입 찾기</AccountItem>
        </AccountOption>
        <SocialLoginBtn>
          <SocialLoginImg></SocialLoginImg>
          <SocialLoginTitle>카카오톡 로그인</SocialLoginTitle>
        </SocialLoginBtn>
      </Wrapper>
    </>
  );
}