import Head from "next/head";
import {
  Wrapper,
  MobileMenu,
  SearchContainer,
  SearchItem,
  MenuContainer,
  MenuWrap,
  MenuTitle,
  ProfileWrap,
  ProfileImg,
  ProfileName,
  MenuTab,
  MenuTabList,
  ContentsContainer,
  ContentsWrap,
  ContentsList,
  ContentsTextWrap,
  ContentsNumber,
  ContentsTitle,
  MoreViewBtn,
  MyMenuContainer,
  MyMenu,
  MyMenuList,
  MyMenuImg,
  MyMenuText,
} from "../../styles/classQuiz01";

export default function ClassQuiz01() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <MobileMenu></MobileMenu>
        <MenuContainer>
          <SearchContainer>
            <SearchItem></SearchItem>
          </SearchContainer>
          <MenuWrap>
            <MenuTitle>마이</MenuTitle>
            <ProfileWrap>
              <ProfileImg></ProfileImg>
              <ProfileName>임정아
                <img src="images/01/arrow_right.png"></img>
              </ProfileName>
            </ProfileWrap>
          </MenuWrap>

          <MenuWrap>
            <MenuTab>
              <MenuTabList>공지사항</MenuTabList>
              <MenuTabList>이벤트</MenuTabList>
              <MenuTabList className="selected">FAQ</MenuTabList>
              <MenuTabList>Q&A</MenuTabList>
            </MenuTab>
          </MenuWrap>
        </MenuContainer>
        <ContentsContainer>
          <ContentsWrap>
            <ContentsList>
              <ContentsTextWrap>
                <ContentsNumber>Q.01</ContentsNumber>
                <ContentsTitle>리뷰 작성은 어떻게 하나요?</ContentsTitle>
              </ContentsTextWrap>
              <MoreViewBtn></MoreViewBtn>
            </ContentsList>
            <ContentsList>
              <ContentsTextWrap>
                <ContentsNumber>Q.02</ContentsNumber>
                <ContentsTitle>리뷰 수정/삭제는 어떻게 하나요?</ContentsTitle>
              </ContentsTextWrap>
              <MoreViewBtn></MoreViewBtn>
            </ContentsList>
            <ContentsList>
              <ContentsTextWrap>
                <ContentsNumber>Q.03</ContentsNumber>
                <ContentsTitle>아이디/비밀번호를 잊어버렸어요</ContentsTitle>
              </ContentsTextWrap>
              <MoreViewBtn></MoreViewBtn>
            </ContentsList>
            <ContentsList>
              <ContentsTextWrap>
                <ContentsNumber>Q.04</ContentsNumber>
                <ContentsTitle>회원탈퇴를 하고싶어요.</ContentsTitle>
              </ContentsTextWrap>
              <MoreViewBtn></MoreViewBtn>
            </ContentsList>
            <ContentsList>
              <ContentsTextWrap>
                <ContentsNumber>Q.05</ContentsNumber>
                <ContentsTitle>출발지 설정은 어떻게 하나요?</ContentsTitle>
              </ContentsTextWrap>
              <MoreViewBtn></MoreViewBtn>
            </ContentsList>
            <ContentsList>
              <ContentsTextWrap>
                <ContentsNumber>Q.06</ContentsNumber>
                <ContentsTitle>비밀번호를 변경하고 싶어요</ContentsTitle>
              </ContentsTextWrap>
              <MoreViewBtn></MoreViewBtn>
            </ContentsList>
          </ContentsWrap>
        </ContentsContainer>
        <MyMenuContainer>
          <MyMenu>
            <MyMenuList>
              <MyMenuImg><img src="images/01/b_menu01.png"></img></MyMenuImg>
              <MyMenuText>홈</MyMenuText>
            </MyMenuList>
            <MyMenuList>
              <MyMenuImg><img src="images/01/b_menu02.png"></img></MyMenuImg>
              <MyMenuText>잇츠로드</MyMenuText>
            </MyMenuList>
            <MyMenuList>
              <MyMenuImg><img src="images/01/b_menu03.png"></img></MyMenuImg>
              <MyMenuText>마이찜</MyMenuText>
            </MyMenuList>
            <MyMenuList>
              <MyMenuImg><img src="images/01/b_menu04.png"></img></MyMenuImg>
              <MyMenuText>마이</MyMenuText>
            </MyMenuList>
          </MyMenu>
        </MyMenuContainer>
      </Wrapper>
    </>
  );
}
